# Generated by Django 5.1.5 on 2025-01-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_art'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'ordering': ['-created_at'], 'verbose_name': 'Analysis Request', 'verbose_name_plural': 'Analysis Requests'},
        ),
        migrations.RemoveField(
            model_name='art',
            name='category',
        ),
        migrations.RemoveField(
            model_name='art',
            name='description',
        ),
        migrations.RemoveField(
            model_name='art',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='art',
            name='status',
        ),
        migrations.AddField(
            model_name='art',
            name='analysis_query',
            field=models.TextField(default='Default product analysis query', help_text='Enter your product analysis query'),
        ),
        migrations.AddField(
            model_name='art',
            name='analysis_result',
            field=models.TextField(blank=True, help_text='Analysis results from YouTube scraper', null=True),
        ),
    ]
