# Generated by Django 5.1.5 on 2025-01-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_art_suggested_queries_art_analysis_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='overall_analysis',
            field=models.TextField(blank=True, help_text='Combined analysis from all sources', null=True),
        ),
    ]
