# Generated by Django 5.1.4 on 2025-01-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedpage',
            name='raw_data',
            field=models.JSONField(default=dict),
        ),
    ]
