# Generated by Django 5.1.5 on 2025-01-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0002_scrapedpage_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingtask',
            name='company_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapingtask',
            name='urls_to_scrape',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
