# Generated by Django 5.1.5 on 2025-01-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0003_scrapingtask_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingtask',
            name='company_name',
        ),
        migrations.AddField(
            model_name='scrapingtask',
            name='keywords',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
