"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--g+309iy&mgr%865^zv6ahaxxa2_5ho2r47r4el$6613w=bi3i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'ytscraper',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'users',
    'webscraper',
    'cassandra.cqlengine.connection',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'project' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

# Social Auth settings
SOCIAL_AUTH_URL_NAMESPACE = 'social'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = 'home'
SOCIAL_AUTH_LOGIN_ERROR_URL = 'login'
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '842002200695-8so8lasrmnep7go3daosnkemi2eti7ea.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

# Login/Logout URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_URL = 'logout'
LOGOUT_REDIRECT_URL = 'login'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
    },
    'loggers': {
        '': {  # Root logger
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
        },
        'ytscraper': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Astra DB Configuration
ASTRA_DB_SECURE_BUNDLE_PATH = './secure-connect-lsm.zip'
ASTRA_DB_CLIENT_ID = 'BIqFUrwjefjTZsMDErzZscZQ'
ASTRA_DB_CLIENT_SECRET = 'Wj0O28bYeNi3TUBSR4P3veJvKQtcqYkC0bxvOIOcm-uckv4vmx0gYg5dIuPGxkeDTSCH8OE7OaP5YDngRo.N8HvNbr+1wNUAsDzyTMYgYo8R-zyk8ORp3JNo0FkT0NY8'
ASTRA_DB_KEYSPACE = 'django_keyspace'

# Add these new settings
os.environ['CQLENG_ALLOW_SCHEMA_MANAGEMENT'] = '1'

# Configure Cassandra connection with additional settings
CASSANDRA_CONNECTION = {
    'secure_connect_bundle': ASTRA_DB_SECURE_BUNDLE_PATH,
    'auth_provider': {
        'username': ASTRA_DB_CLIENT_ID,
        'password': ASTRA_DB_CLIENT_SECRET
    },
    'keyspace': ASTRA_DB_KEYSPACE,
    'connect_timeout': 5,
    'request_timeout': 5,
    'protocol_version': 4,
    'control_connection_timeout': 5,
    'connection_class': 'cassandra.cluster.SessionManager',
    'retry_connect': True,
    'metrics_enabled': False,
    'compression': True,
    'idle_heartbeat_interval': 30,
}

# Add these settings
CASSANDRA_DRIVER_SETTINGS = {
    'protocol_version': 4,
    'connect_timeout': 30,
    'request_timeout': 30,
    'control_connection_timeout': 30,
    'max_schema_agreement_wait': 20,
    'idle_heartbeat_interval': 30,
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'users': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Add Redis caching
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 3600,
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
            'CULL_FREQUENCY': 3,
        }
    }
}

# Astra DB Configuration
ENABLE_ASTRA_SYNC = os.getenv('ENABLE_ASTRA_SYNC', 'False').lower() == 'true'
# For syncing: ENABLE_ASTRA_SYNC=true python manage.py runserver
# For no syncing: ENABLE_ASTRA_SYNC=false python manage.py runserver (or just don't set it)

# set ENABLE_ASTRA_SYNC=true
# python manage.py runserver
GEMINI_API_KEY = 'AIzaSyDNI197dcPy4BbYUThYMdXWQaEpcYBrms4'

# Google Custom Search API settings
GOOGLE_API_KEY = 'AIzaSyC-rLN8dXEVdbvlY0fSl_e_6BEov6cLrDs'
GOOGLE_CSE_ID = '673c8dccaf5db4b0d'